### ISSUE TITLE
Uwsgi fails to install on cygwin because of gcc --werror --rdynamic, works if removing those

### ISSUE THREAD

**Issue by ddorian** [unbit/uwsgi#878] opened 2015-04-06 16:53 UTC
both cygwin x86, x64
python 2.7
pip 6.0.8 (but i guess it doesn't matter)
gcc 4.9.2

doing pip install uwsgi:
 *** uWSGI compiling server core ***

    [gcc] core/utils.o

    ----------------------------------------
    Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-63Vzrc/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5dqi2h-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-63Vzrc/uwsgi

Which means, it has "werror", which fails on warning. 
If I remove that from uwsgiconfig.py, it continues happily until:

It fails again, because gcc doesn't have the "rdyanmic" option: So I remove it from that.
self.libs = ['-lpthread', '-lm', '-rdynamic']
And then it finishes. Some testing with running my app seems to be working 'ok'.

Thank you

**Comment by xrmx** [comment] 2015-04-07 08:08
@ddorian thanks for reporting. Any chanche you pastebin the warnings please?

**Comment by ddorian** [comment] 2015-04-07 08:50
Without changing anything:
http://pastebin.com/t5YLbSrY

After removing "-Werror" from uwsgiconfig.py:633 I get this error:
http://pastebin.com/fkSKUSBz

After removing "-rdynamic" in uwsgiconfig.py:705, it completed.

**Comment by xrmx** [comment] 2015-04-07 09:56
Does something like this helps? First hunk is a hack but the second should be fine to go in. I've diffed against later git so am not sure it would apply cleanly.

```
diff --git a/uwsgi.h b/uwsgi.h
index ed3c006..bae23ee 100755
--- a/uwsgi.h
+++ b/uwsgi.h
@@ -234,6 +234,11 @@ extern "C" {
 
 
 #include <pwd.h>
+#ifdef __CYGWIN__
+#ifdef _POSIX_C_SOURCE
+#undef _POSIX_C_SOURCE
+#endif
+#endif
 #include <grp.h>
 
 
diff --git a/uwsgiconfig.py b/uwsgiconfig.py
index f4bc2db..ea346e8 100644
--- a/uwsgiconfig.py
+++ b/uwsgiconfig.py
@@ -796,6 +796,9 @@ class uConf(object):
             if GCC in ('clang',):
                 self.libs.remove('-rdynamic')
 
+        if uwsgi_os.startswith('CYGWIN'):
+            self.libs.remove('-rdynamic')
+
         # compile extras
         extras = self.get('extras', None)
         if extras:
```

**Comment by rcarmo** [comment] 2016-01-31 11:30
I can confirm this helps. It's been a year now, so I'm curious as to why this wasn't merged...

**Comment by xrmx** [comment] 2016-01-31 11:32
@rcarmo simply because nobody confirmed in a year that the patch worked

**Comment by rcarmo** [comment] 2016-01-31 11:46
Oh, there was one more thing. I added `self.cflags.remove('-Werror') after removing `-rdynamic`. Thanks!

**Comment by rcarmo** [comment] 2016-01-31 11:49
Also, for the record, this is the version I built:
```
*** Starting uWSGI 2.0.12 (64bit) on [Sun Jan 31 11:48:26 2016] ***
compiled with version: 4.9.3 on 31 January 2016 11:44:55
os: CYGWIN_NT-10.0-2.3.1(0.291/5/3) 2015-11-14 12:44
nodename: unexpected
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /cygdrive/c/Users/rucarmo/OneDrive/Development/uwsgi-2.0.12
detected binary path: /cygdrive/c/Users/rucarmo/OneDrive/Development/sushy/env/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
The -s/--socket option is missing and stdin is not a socket.
```

**Comment by xrmx** [comment] 2016-02-01 13:42
@rcarmo please post the warnings, removing -Werror is really the last option.

**Comment by rcarmo** [comment] 2016-02-01 17:30
Hello there again,

In Cygwin's case at least initgroups needs to be explicitly defined, but I'm not sure which header file is required (initgroups has been somewhat of a recurring topic since 2002, IIRC).

Here's the error:

```
*** uWSGI compiling server core ***
[gcc] core/utils.o
core/utils.c: In function ‘uwsgi_as_root’:
core/utils.c:848:4: error: implicit declaration of function ‘initgroups’ [-Werror=implicit-function-declaration]
    if (initgroups(uidname, uwsgi.gid)) {
    ^
cc1: all warnings being treated as errors
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
```

There may be more errors even if this is fixed - at this point I have a working build and am focusing on using it, so systematically going through the source files to add missing `#ifdefs` is a secondary priority and I cannot commit to a date for a "complete" fix (which I might do "wrong" for some reason I'm not aware of).

**Comment by rcarmo** [comment] 2016-02-01 23:22
I had a couple of spare minutes to test a change to `utils.c` and updated my pull request. By defining `initgroups` it compiles cleanly - I tried adding various Cygwin-specific header files to `utils.c` and to the main header file (including the obvious `cygwin/grp.h`), but to no avail (and only `utils.c` required the function to be defined).

It now complies cleanly with `-Werror` active.

**Closed** 2016-02-02 08:51 UTC
Labels: needs review, patch attached
