### ISSUE TITLE
py-autoreload does not handle not-existing imports in try-except blocks

### ISSUE THREAD

**Issue by timesqueezer** [unbit/uwsgi#1975] opened 2019-02-05 21:38 UTC
Noticed that uwsgi segfaults when importing a specific module.
The relevant output:
```
/usr/lib/libc.so.6(+0x37e00) [0x7f8a5b6a6e00]
/usr/lib/libpython3.7m.so.1.0(PyBytes_AsString+0x4) [0x7f8a592b93b4]
/usr/lib/uwsgi/python_plugin.so(uwsgi_python_autoreloader_thread+0x1a0) [0x7f8a59531930]
```
After some investigation I found the culprit here:
[maxminddb](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/master/maxminddb/__init__.py)

The relevant code section:
```
try:
    import maxminddb.extension
except ImportError:
    maxminddb.extension = None
```

I currently don't have the time to dive into the python_autoreload source but I verified that this import caused the issue and listing in it py-auto-reload-ignore resolves it.

**Comment by xrmx** [comment] 2019-02-05 22:15
Duplicate of #1825 , please give it a try to uwsgi-2.0 branch

**Closed by xrmx** 2019-02-05 22:15 UTC
