### ISSUE TITLE
wheel build randomly fails on cpython 3.10

### ISSUE THREAD

**Issue by starenka** [unbit/uwsgi#2471] opened 2022-08-01 18:50 UTC
this issue gives me headaches for a while now, but i just realized that it builds/fails "randomly" on the same machine in different (empty) venvs....

a brand new empty venv compiles:

```
starenka /tmp % mktmpenv 
created virtual environment CPython3.10.5.final.0-64 in 91ms
  creator CPython3Posix(dest=/data/.envs/tmp-cecb352660d5c5e, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/starenka/.local/share/virtualenv)
    added seed packages: pip==22.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /data/.envs/tmp-cecb352660d5c5e/bin/predeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-cecb352660d5c5e/bin/postdeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-cecb352660d5c5e/bin/preactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-cecb352660d5c5e/bin/postactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-cecb352660d5c5e/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.

(tmp-cecb352660d5c5e) starenka /data/.envs/tmp-cecb352660d5c5e % pip install uwsgi --no-cache-dir        
Collecting uwsgi
  Downloading uwsgi-2.0.20.tar.gz (804 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.9/804.9 kB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py) ... done
  Created wheel for uwsgi: filename=uWSGI-2.0.20-cp310-cp310-linux_x86_64.whl size=588854 sha256=f67bf4e2cc1bfafd609e9bdd0aa22c33434a727de5a0a559e97399dbcf6211e9
  Stored in directory: /tmp/pip-ephem-wheel-cache-u09_ly1t/wheels/06/05/96/5ee3e21875a5cab911fdbb7d8100b24fbd639c55a65b5b6ccb
Successfully built uwsgi
Installing collected packages: uwsgi
Successfully installed uwsgi-2.0.20
(tmp-cecb352660d5c5e) starenka /data/.envs/tmp-cecb352660d5c5e % python
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux
```

and now another empty env and it fails:

```
starenka /data/.envs % mktmpenv                                
created virtual environment CPython3.10.5.final.0-64 in 103ms
  creator CPython3Posix(dest=/data/.envs/tmp-3d9878a876d85c2, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/starenka/.local/share/virtualenv)
    added seed packages: pip==22.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /data/.envs/tmp-3d9878a876d85c2/bin/predeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-3d9878a876d85c2/bin/postdeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-3d9878a876d85c2/bin/preactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-3d9878a876d85c2/bin/postactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-3d9878a876d85c2/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.

(tmp-3d9878a876d85c2) starenka /data/.envs/tmp-3d9878a876d85c2 % pip install uwsgi --no-cache-dir
Collecting uwsgi
  Downloading uwsgi-2.0.20.tar.gz (804 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.9/804.9 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      copying uwsgidecorators.py -> build/lib
      /data/.envs/tmp-3d9878a876d85c2/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      using profile: buildconf/default.ini
      detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/11/include', '/usr/local/include', '/usr/include/x86_64-linux-gnu', '/usr/include']
      Patching "bin_name" to properly install_scripts dir
      detected CPU cores: 8
      configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY  -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_UUID -DUWSGI_VERSION="\"2.0.20\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="20" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -I/usr/include/libxml2 -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
      *** uWSGI compiling server core ***
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/utils.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] core/protocol.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/socket.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/logging.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/master.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/master_utils.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/emperor.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/notify.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/mule.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] core/subscription.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/stats.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/sendfile.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/async.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/master_checks.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/fifo.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/offload.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/io.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/static.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] core/websockets.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/spooler.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/snmp.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/exceptions.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/config.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/setup_utils.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/clock.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] core/init.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/buffer.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/reader.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/writer.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/alarm.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/cron.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/hooks.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/plugins.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/lock.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] core/cache.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/daemons.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/errors.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/hash.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/master_events.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/chunked.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/queue.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/event.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/signal.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/strings.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/progress.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/timebomb.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/ini.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/fsmon.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/mount.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/metrics.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/plugins_builder.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/sharedarea.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/rpc.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/gateway.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] core/loop.o
      core/metrics.c: In function ‘uwsgi_metric_set_max’:
      core/metrics.c:706:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
        706 |     if (value > *um->value)
            |     ^~
      In file included from core/metrics.c:1:
      ./uwsgi.h:436:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
        436 | #define uwsgi_rwunlock(x) uwsgi.lock_ops.rwunlock(x)
            |                           ^~~~~
      core/metrics.c:708:9: note: in expansion of macro ‘uwsgi_rwunlock’
        708 |         uwsgi_rwunlock(uwsgi.metrics_lock);
            |         ^~~~~~~~~~~~~~
      core/metrics.c: In function ‘uwsgi_metric_set_min’:
      core/metrics.c:714:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
        714 |     if ((value > um->initial_value || 0) && value < *um->value)
            |     ^~
      In file included from core/metrics.c:1:
      ./uwsgi.h:436:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
        436 | #define uwsgi_rwunlock(x) uwsgi.lock_ops.rwunlock(x)
            |                           ^~~~~
      core/metrics.c:716:9: note: in expansion of macro ‘uwsgi_rwunlock’
        716 |         uwsgi_rwunlock(uwsgi.metrics_lock);
            |         ^~~~~~~~~~~~~~
      [thread 7][x86_64-linux-gnu-gcc -pthread] core/cookie.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] core/querystring.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] core/rb_timers.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] core/transformations.o
      [thread 1][x86_64-linux-gnu-gcc -pthread] core/uwsgi.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] proto/base.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] proto/uwsgi.o
      [thread 7][x86_64-linux-gnu-gcc -pthread] proto/http.o
      [thread 5][x86_64-linux-gnu-gcc -pthread] proto/fastcgi.o
      [thread 6][x86_64-linux-gnu-gcc -pthread] proto/scgi.o
      [thread 3][x86_64-linux-gnu-gcc -pthread] proto/puwsgi.o
      [thread 2][x86_64-linux-gnu-gcc -pthread] lib/linux_ns.o
      [thread 0][x86_64-linux-gnu-gcc -pthread] core/zlib.o
      [thread 4][x86_64-linux-gnu-gcc -pthread] core/regexp.o
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for uwsgi
  Running setup.py clean for uwsgi
Failed to build uwsgi
Installing collected packages: uwsgi
  Running setup.py install for uwsgi ... done
Successfully installed uwsgi-2.0.20
```

any clues?

**Comment by xrmx** [comment] 2022-08-01 19:39
Please try the uwsgi-2.0 branch.

**Comment by starenka** [comment] 2022-08-02 08:09
works with latest commit on that branch tho...

```
Collecting git+https://github.com/unbit/uwsgi.git@1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824
  Cloning https://github.com/unbit/uwsgi.git (to revision 1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824) to /tmp/pip-req-build-1r34d0k1
  Running command git clone --filter=blob:none --quiet https://github.com/unbit/uwsgi.git /tmp/pip-req-build-1r34d0k1
  Running command git rev-parse -q --verify 'sha^1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824'
  Running command git fetch -q https://github.com/unbit/uwsgi.git 1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824
  Running command git checkout -q 1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824
  Resolved https://github.com/unbit/uwsgi.git to commit 1bb9ad77c6d2d310c2d6d1d9ad62de61f725b824
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: uWSGI
  Building wheel for uWSGI (setup.py) ... done
  Created wheel for uWSGI: filename=uWSGI-2.0.20-cp310-cp310-linux_x86_64.whl size=589261 sha256=fb0fab497d057b2139f6c3645d8d03ccb9ccb7ec4a9d712ce52cae4376663686
  Stored in directory: /tmp/pip-ephem-wheel-cache-v4mr8w1h/wheels/18/77/82/fea8a96501c721d7a7953df90bf3adc7f81914a405def602bd
Successfully built uWSGI
Installing collected packages: uWSGI
Successfully installed uWSGI-2.0.20
```

**Comment by woodruffw** [comment] 2022-08-11 16:18
Hey there! A `pip-audit` user has reported some spurious auditing failures that look like they're connected to this. Is there a roadmap or schedule for a bugfix release that includes the associated fix here?

**Comment by xrmx** [comment] 2022-08-12 07:39
@woodruffw nope, no roadmap

**Comment by divad** [comment] 2022-08-30 16:34
I think I'm hitting this issue too, does this seem to be the same issue?

```  × Running setup.py install for uwsgi did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      /tmp/fut_venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'descriptions'
        warnings.warn(msg)
      running install
      /tmp/fut_venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      using profile: buildconf/default.ini
      detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/10/include', '/usr/local/include', '/usr/include/x86_64-linux-gnu', '/usr/include']
      Patching "bin_name" to properly install_scripts dir
      detected CPU cores: 4
      configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY  -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_UUID -DUWSGI_VERSION="\"2.0.20\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="20" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -I/usr/include/libxml2 -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
      *** uWSGI compiling server core ***
      [thread 2][gcc -pthread] core/utils.o
      [thread 1][gcc -pthread] core/protocol.o
      [thread 3][gcc -pthread] core/socket.o
      [thread 0][gcc -pthread] core/logging.o
      [thread 1][gcc -pthread] core/master.o
      [thread 0][gcc -pthread] core/master_utils.o
      [thread 3][gcc -pthread] core/emperor.o
      [thread 1][gcc -pthread] core/notify.o
      [thread 1][gcc -pthread] core/mule.o
      [thread 2][gcc -pthread] core/subscription.o
      [thread 0][gcc -pthread] core/stats.o
      [thread 1][gcc -pthread] core/sendfile.o
      [thread 3][gcc -pthread] core/async.o
      [thread 1][gcc -pthread] core/master_checks.o
      [thread 0][gcc -pthread] core/fifo.o
      [thread 2][gcc -pthread] core/offload.o
      [thread 3][gcc -pthread] core/io.o
      [thread 0][gcc -pthread] core/static.o
      [thread 1][gcc -pthread] core/websockets.o
      [thread 2][gcc -pthread] core/spooler.o
      [thread 1][gcc -pthread] core/snmp.o
      [thread 0][gcc -pthread] core/exceptions.o
      [thread 3][gcc -pthread] core/config.o
      [thread 2][gcc -pthread] core/setup_utils.o
      [thread 1][gcc -pthread] core/clock.o
      [thread 0][gcc -pthread] core/init.o
      [thread 2][gcc -pthread] core/buffer.o
      [thread 1][gcc -pthread] core/reader.o
      [thread 3][gcc -pthread] core/writer.o
      [thread 0][gcc -pthread] core/alarm.o
      [thread 2][gcc -pthread] core/cron.o
      [thread 1][gcc -pthread] core/hooks.o
      [thread 0][gcc -pthread] core/plugins.o
      [thread 3][gcc -pthread] core/lock.o
      [thread 2][gcc -pthread] core/cache.o
      [thread 0][gcc -pthread] core/daemons.o
      [thread 1][gcc -pthread] core/errors.o
      [thread 3][gcc -pthread] core/hash.o
      [thread 1][gcc -pthread] core/master_events.o
      [thread 3][gcc -pthread] core/chunked.o
      [thread 0][gcc -pthread] core/queue.o
      [thread 1][gcc -pthread] core/event.o
      [thread 3][gcc -pthread] core/signal.o
      [thread 0][gcc -pthread] core/strings.o
      [thread 2][gcc -pthread] core/progress.o
      [thread 1][gcc -pthread] core/timebomb.o
      [thread 2][gcc -pthread] core/ini.o
      [thread 3][gcc -pthread] core/fsmon.o
      [thread 0][gcc -pthread] core/mount.o
      [thread 1][gcc -pthread] core/metrics.o
      [thread 2][gcc -pthread] core/plugins_builder.o
      [thread 3][gcc -pthread] core/sharedarea.o
      [thread 0][gcc -pthread] core/rpc.o
      [thread 2][gcc -pthread] core/gateway.o
      [thread 0][gcc -pthread] core/loop.o
      [thread 3][gcc -pthread] core/cookie.o
      [thread 2][gcc -pthread] core/querystring.o
      [thread 1][gcc -pthread] core/rb_timers.o
      [thread 0][gcc -pthread] core/transformations.o
      [thread 3][gcc -pthread] core/uwsgi.o
      [thread 2][gcc -pthread] proto/base.o
      [thread 1][gcc -pthread] proto/uwsgi.o
      [thread 0][gcc -pthread] proto/http.o
      [thread 2][gcc -pthread] proto/fastcgi.o
      [thread 1][gcc -pthread] proto/scgi.o
      [thread 2][gcc -pthread] proto/puwsgi.o
      [thread 1][gcc -pthread] lib/linux_ns.o
      [thread 0][gcc -pthread] core/zlib.o
      [thread 2][gcc -pthread] core/regexp.o
      [thread 1][gcc -pthread] core/routing.o
      [thread 0][gcc -pthread] core/yaml.o
      [thread 2][gcc -pthread] core/ssl.o
      [thread 0][gcc -pthread] core/legion.o
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> uwsgi
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
command exited with a non-zero return code```

**Comment by francoisfreitag** [comment] 2022-10-04 10:20
Could be a duplicate of https://github.com/unbit/uwsgi/issues/2398.

**Closed** 2022-10-24 16:23 UTC
